name: metasoft
favicon: null
layout_spectrum: 0.13057
typography_spectrum: 0.81288
title: Metasoft Solutions Pvt. Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffdc98'
    - '#3c549a'
    - '#18c2a5'
    - '#d74681'
    - '#090504'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.8264263088349253
  rhythmicContrast: 0.5
purpose: []
